"""add property goals

Revision ID: cc57c6f551be
Revises: 0001_initial
Create Date: 2026-06-21 19:04:42.653555

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'cc57c6f551be'
down_revision: str | Sequence[str] | None = '0001_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_goals',
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('max_price_sek', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('min_rooms', sa.Integer(), nullable=False),
    sa.Column('max_monthly_fee_sek', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('time_horizon_years', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_goals'))
    )
    op.create_index(op.f('ix_property_goals_area'), 'property_goals', ['area'], unique=False)
    op.create_index(op.f('ix_property_goals_city'), 'property_goals', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_goals_city'), table_name='property_goals')
    op.drop_index(op.f('ix_property_goals_area'), table_name='property_goals')
    op.drop_table('property_goals')
    # ### end Alembic commands ###